# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(blank=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('date_of_birth', models.DateField(blank=True)),
                ('email', models.CharField(max_length=120)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('slug', models.CharField(blank=True, max_length=6)),
                ('status', models.CharField(blank=True, max_length=3)),
                ('picture', models.ImageField(upload_to='profiles')),
                ('address_book', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_book', to='address.AddressBook')),
            ],
        ),
        migrations.CreateModel(
            name='MemberEmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True)),
                ('date_to', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
                ('current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=3)),
                ('status_text', models.CharField(max_length=80)),
            ],
        ),
    ]
