# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstatus',
            name='status_type',
            field=models.CharField(choices=[('V', 'Valid'), ('I', 'Intermediary'), ('F', 'Final')], default='V', max_length=1),
        ),
    ]
