# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20171019_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberstatus',
            name='language',
            field=models.CharField(default='en-US', max_length=2),
            preserve_default=False,
        ),
    ]
